### PR TITLE
Removing Wear service to lower ram usage.

### PR DESCRIPTION
**Pull request by mikhoul**
I removed Wear service to lower the memory usage since Wear adoption seem to be pretty low.

https://mashable.com/article/android-wear-is-not-dead/

### CODE REVIEW

**Comment by fabmazz** [comment]
Hello @mikhoul and thank you for the work you did on analyzing the performance of the app.
Disabling wear service should lower RAM usage, though I still don't know if the wear service needs google stuff to work. In any case, some people might need it, and it wouldn't be a good thing to disable it permanently from the code base.
As the issue page goes, I have no idea at the moment how to add that, I fear that, since this repo is a fork, github wouldn't let you have it. About this, the code should really be moved to a separate repo with a different name, and also the title of the app should be changed.
I am not a developer, I simply downloaded the source code of the Timber app when it disappeared from F-Droid, then built it by myself and later I wanted to put it back to F-Droid.

**Comment by mikhoul** [comment]
I'm not a Java developer too but I will do my best to clean up the code in my part time.

The wear adoption is very low from what I've read so sure maybe few users use it but IMO lowering the memory usage is better since it prevent the app from being discarded when the screen-lock is on.

Also the wear service need Google Play services to sync...
 
image


To enable the Issue:  Go to the main page of the Repo and **click on Settings**:

image

Scroll down till you see the "**Features**" section and tick the box beside "**Issues**"
image

Changing the name of the repo is easy : 
image

So maybe you could just add the PR I've done that you feel comfortable with it this way the other users could profit of them too :smile: 

Wishing you a great week-end !  :octocat:

**Comment by fabmazz** [comment]
Thank you for your instructions, I have now enabled the issues.

I failed to mention before that this app is not developed anymore, as the original author created a new version in Kotlin. I appreciate your enthusiasm in the analysis of the code, and instead of spending time on this app, it would be much better to create a FOSS version of the new one (which is called TimberX). 

I'll still accept gladly the results of your work on the maintenance of this app.

If you can tell me that the code from this PR builds and the app runs with no problems, I'll accept this pull request.

**Comment by mikhoul** [comment]
I've seen the new one but it will take years to have the same functions and the stability of the original Timber.

Sadly  there is lot of bug and it crash a lot and the last release was in February... the dev mus be busy with his daytime job so I would not hold my breath. 

________________________________________________________

No problem before sending you PR I will test them thoroughly. :smile:

**Pull request merged**
